services:
  - type: web
    name: tree-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: tree-system-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET
        generateValue: true
      - key: DB_FILE
        value: /app/data/database.json
      - key: INITIAL_ADMIN_USERNAME
        sync: false
      - key: INITIAL_ADMIN_PASSWORD
        sync: false
